### ISSUE TITLE
[BUILD][NDI] Problem with the file "NdiMediaEditorModule.cpp"

### ISSUE THREAD

**Issue by brasegajames** [ue4plugins/NdiMedia#1]
Hi,

I got to use this plugin on Linux and Windows.
On both platforms i got the same kind of errors. When I included the plugin into my cpp project, unreal asked me to build the plugin. Then, on both platform, i got the same problem, there is the output log on windows : 

> C:\Users\Alexandre\Documents\Unreal Projects\MyProjectCPP_01\Plugins\NdiMedia\Source\NdiMediaEditor\Private\NdiMediaEditorModule.cpp(22): error C2061: syntax error: identifier 'NdiMediaEditor'
> C:\Users\Alexandre\Documents\Unreal Projects\MyProjectCPP_01\Plugins\NdiMedia\Source\NdiMediaEditor\Private\NdiMediaEditorModule.cpp(22): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

The same kind of error occurs on Linux, saying that this line has a problem: 
`
IMPLEMENT_MODULE(FNdiMediaEditorModule, NdiMediaEditor);`

On linux, the error log is as follows : 

> In file included from /media/jacques/home/jacques/EpicGames/UnrealEngine/Engine/Plugins/Media/NdiMedia/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/NdiMediaEditor/Module.NdiMediaEditor.cpp:2:
> /media/jacques/home/jacques/EpicGames/UnrealEngine/Engine/Plugins/Media/NdiMedia/Source/NdiMediaEditor/Private/NdiMediaEditorModule.cpp:22:41: error: unknown type name 'NdiMediaEditor'
> IMPLEMENT_MODULE(FNdiMediaEditorModule, NdiMediaEditor);
>                                         ^
> /media/jacques/home/jacques/EpicGames/UnrealEngine/Engine/Plugins/Media/NdiMedia/Source/NdiMediaEditor/Private/NdiMediaEditorModule.cpp:22:1: error: C++ requires a type specifier for all
>       declarations
> IMPLEMENT_MODULE(FNdiMediaEditorModule, NdiMediaEditor);
> ^~~~~~~~~~~~~~~~
> 2 errors generated.

The two tests were done with the latest SDK version we could get on the NewTek website, and the latest version of your plugin, with the latest version of Unreal engine 4.13 (Linux), and 4.13.1 (Win).

Thanks for reading.

Regards,

Alexandre ADAM

**Comment by gmpreussner** [comment]
Hmm... did you run /UE4/GenerateProjectFiles.bat after cloning the GitHub repository into your project?

**Comment by jacques-hybrid** [comment]
Hi,

Thanks for your help. Generating the project files did not change the build errors but we finally managed to build the plugin by including **"Editor.h"** in the file **NdiMediaEditorModule.cpp**
I don't know why we have to do this though, we are exploring the Unreal Engine since 2 weeks only...
Does this include make sense for you ? Is there a better solution ?

Anyway, the plugin works on Windows and also Linux after some minor modifications :)
We are now eagerly waiting for the NDI output plugin ! Do you have an ETA by any chance ?

Thank you.

**Comment by gmpreussner** [comment]
> We are now eagerly waiting for the NDI output plugin ! Do you have an ETA by any chance ?

Newtek has an implementation for output, but I haven't seen it yet. Video output from UE4 is something I'd like to add to the Media Framework API, but I haven't had time yet. I will probably be able to finish it for 4.15 though (and in the Master branch likely before the end of the year).

**Comment by gmpreussner** [comment]
> we finally managed to build the plugin by including "Editor.h"

I think the problem is that _ModuleManager.h_ was missing. I fixed this in the new version (which isn't on GitHub yet).

**Comment by gmpreussner** [comment]
> Anyway, the plugin works on Windows and also Linux after some minor modifications

The next version should work much better and out of the box. It will include the pre-compiled libraries and DLLs for Windows, macOS, iOS, and Linux.

**Comment by num3ric** [comment]
Adding "Editor.h" to NdiMediaEditorModule.cpp also fixed the compile error on my end.

However, I am still having trouble launching the project where the 'NdiMedia' module could not be loaded.

**Comment by num3ric** [comment]
Ah sorry, just need to manually copy the .dll, as described in the ReadMe. All good! :)

**Comment by gmpreussner** [comment]
Yep. The next version will contain the required DLLs.
