### ISSUE TITLE
Precompiled Header Issues

### ISSUE THREAD

**Issue by ericapenk** [ue4plugins/NdiMedia#10]
All source files in module "NdiMediaFactory" must include the same precompiled header first.  Currently "A:\Unreal Projects\NDI_Test_2\Plugins\NdiMedia-master\Source\NdiMediaFactory\Public\NdiMediaSettings.h" is included by most of the source files.  The following source files are not including "A:\Unreal Projects\NDI_Test_2\Plugins\NdiMedia-master\Source\NdiMediaFactory\Public\NdiMediaSettings.h" as their first include:	NDI_Test_2	A:\Unreal Projects\NDI_Test_2\Intermediate\ProjectFiles\EXEC	1	

Attempted moving the "NdiMediaSettings.h" include statement to the top of the include statements in NdiMediaFactoryModule.cpp and that introduced several warnings.

The next precompile error was with the NdiMedia module.  There's several cpp  files with several headers to choose from, so that's still not resolved.

Some context:

I downloaded the newest NDI 2 SDK, created a new 4.13.2 c++ project (also tried 4.14 for good measure), created a Plugins folder, dropped the NdiMedia-master folder downloaded from github today into the plugins folder, right clicked the .uproject > Generate Visual Studio project files (just in case).  Then I started compiling and trying to fix include statements.  Is there anything I'm missing?  I have not placed any additional files into any other directories, is that something I need to do?  

Thanks so much!

**Comment by gmpreussner** [comment]
Hi Erica, please do not sync the Master branch, but sync to the label of your Engine version instead, i.e. 4.13.1 or 4.14. The code in Master compiles only against my working branch of UE4, and that is often even newer than the UE4 Master branch on GitHub.

**Comment by gmpreussner** [comment]
https://github.com/ue4plugins/NdiMedia/releases

**Comment by ericapenk** [comment]
ok, and where can I find the NdiMedia.dll, NdiMediaEditor.dll, and the
NdiMediaFactory.dll ? Says they're either missing or made with the wrong
version.  At least for the 4.14 version I can say I know it's the right
version.

I'm assuming I'm supposed to place those in the Binaries/Win64 folder like
I did with Processing.NDI.Lib.x64.dll previously.  I currently don't have
the Processing dll in there because it's not erroring out on it like it was
the previous time.

*ERICA PENK*
*TRICK 3D | TECHNICAL MANAGER*
*w *www.trick3d.com *| e* erica.penk@trick3d.com

**Comment by gmpreussner** [comment]
You have to compile the NdiMedia plug-in code as part of your Engine, or your project. The DLLs will then be created. The Processing.NDI.xxxx DLLs are already included in the plug-in. You do not need to download them separately, nor do you need to copy them to Binaries. This all happens automatically as part of compiling the plug-in.

There is currently no ready-to-use binary version of NdiMedia, so you have to compile yourself. When I find some time, I'll publish NdiMedia on the UE4 Marketplace, but this may not happen before 4.15.

**Comment by gmpreussner** [comment]
PS: The easiest way to compile the plug-in is to either...

a) create a code project and place the plug-in into /YourProject/Plugins/NdiMedia, or
b) compile the entire Engine from source and place the plug-in into /Engine/Plugins/NdiMedia

**Comment by ericapenk** [comment]
Ah I dumped the contents into the Plugin folder.  I was missing the
NdiMedia layer in the hierarchy when I was compiling.

Did the new SDK address the roaming port issue?

I typed in:

 127.0.0.1:5353 into the NdiMediaSource but it's still a black screen.

*ERICA PENK*
*TRICK 3D | TECHNICAL MANAGER*
*w *www.trick3d.com *| e* erica.penk@trick3d.com

**Comment by gmpreussner** [comment]
The roaming port issue is something that needs to be addressed in the NDI server. The test applications that ship with the latest SDK should have static ports now.

That being said, I had a discussion with Newtek about this, and the intent is that media sources should be looked up by name, not by IP:Port. It is assumed that NDI source names are unique per machine. I am going to change the NdiMedia source to use name based lookup instead.
