### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by Harvey3141** [ue4plugins/NdiMedia#12]
Hi, 

I can't find any instructions oh how to actually implement the plugin. Can it be done using blueprints or just in code? 

Thanks,

Harvey

**Comment by DylanFilingeri** [comment]
I'm wondering the same thing. I don't see any documentation anywhere on how to actually implement this into a project.

**Comment by gmpreussner** [comment]
Sorry, there are no instructions yet. Hopefully for 4.17 I'll have more time.

There are two Blueprint classes: NdiMediaSource and NdiMediaFinder. Follow the instructions in the [Media Framework How-To](https://docs.unrealengine.com/latest/INT/Engine/MediaFramework/HowTo/) on how to set up media playback in UE4 in general.
