### ISSUE TITLE
[4.15.1] All source files in module "NdiMediaFactory" must include the same precompiled header first

### ISSUE THREAD

**Issue by GundlackFlorian** [ue4plugins/NdiMedia#13]
Hello,
When i try to compile my project with the version 4.15.1 (and the version 4.15 of the plugin) i get the following error:

`EXEC : error : All source files in module "NdiMediaFactory" must include the same precompiled header first.  Currently "C:\Users\FLOGU\Desktop\NDI_Test\Plugins\NdiMedia-4.15\Source\NdiMediaFactory\Public\NdiMediaSettings.h" is included by most of the source files.  The following source files are not including "C:\Users\FLOGU\Desktop\NDI_Test\Plugins\NdiMedia-4.15\Source\NdiMediaFactory\Public\NdiMediaSettings.h" as their first include:
1>
1>C:\Users\FLOGU\Desktop\NDI_Test\Plugins\NdiMedia-4.15\Source\NdiMediaFactory\Private\NdiMediaFactoryModule.cpp (including C:\Program Files\Epic Games\UE_4.15\Engine\Source\Runtime\Core\Public\CoreMinimal.h)`

I tried with the "normal" version of Unreal, and the source compiled one.

**Comment by GundlackFlorian** [comment]
Hi !

Your fix ( 30fef7312f571b37a535ce6f32e20cffd0912dc1 ), doesn't compile for me (UnrealBuildTool.ReadOnlyTargetRules error).

I tried a lot of commits and found a working (but old) one that work with 4.15.1 as project plugin:
https://github.com/ue4plugins/NdiMedia/commit/37f611c58f8fbf57004845fa61fb4443d02a4661

**Comment by gmpreussner** [comment]
The code that's in Github now requires 4.16. To compile against 4.15, you need to copy only the relevant lines in the three Build.cs files.

**Comment by GundlackFlorian** [comment]
Updated Build.cs files, it compiles now. But editor crashes at launch.

I edit this comment later with a log and eventually a fix if i find one.

**Comment by gmpreussner** [comment]
What's the callstack? Make sure you pull the 4.15 tagged version and only update the Build.cs files. Do not pull down the latest ThirdParty files in particular; the API changed.

**Comment by GundlackFlorian** [comment]
You mean https://github.com/ue4plugins/NdiMedia/tree/4.15 ?

With this one i have the header issue mentioned im my first comment.

Edit:

To reproduce:
- Create a c++ project with unreal 4.15.1 (not tested with the compiled)
- Create a Plugins folder in root of the project folder
- git clone https://github.com/ue4plugins/NdiMedia.git to the project folder
- git checkout 4.15
- regenerate visual studio files
- compile

**Comment by gmpreussner** [comment]
You forgot to apply the latest **changes to the Build.cs files on top of the 4.15 checkout**

**Comment by gmpreussner** [comment]
Also, if you have Engine code, you can make it an Engine plug-in instead (clone into /Engine/Plugins). Then you don't have to make any changes to the Build.cs files.

The change in the Build.cs files is the following additional line:

`PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;`

You have to [add this line](https://github.com/ue4plugins/NdiMedia/blob/master/Source/NdiMedia/NdiMedia.Build.cs#L13) to each of the three Build.cs files.

**Comment by GundlackFlorian** [comment]
Hi !
Sorry for the late reply. I just tested to add the three lines:
On the compiled version of the engine (release branch, compiled yesterday) it works fine.

But on the "regular" version i have a crash on start, here is the full log folder:

[UE4CC-Windows-70EA04F040A97BB570CF2A990B13FCDA_0000.zip](https://github.com/ue4plugins/NdiMedia/files/944559/UE4CC-Windows-70EA04F040A97BB570CF2A990B13FCDA_0000.zip)

(Sames steps a above, but just added the lines before compiling)

**Comment by GundlackFlorian** [comment]
Hi,
My bad, just tested on empty project and works fine.

After deleting all the references to the "old" ndi plugin blueprints it worked.
I close the issue.

Thanks again !
