### ISSUE TITLE
[4.15.1 And 4.16] Packaging for linux: Undefined reference

### ISSUE THREAD

**Issue by GundlackFlorian** [ue4plugins/NdiMedia#14]
Hi !

When i try to package a project for Linux (Windows cross compiling) with NdiMedia as project plugin, the build fails with undefined reference to somes functions.

But it works perfectly with Win64, and on Mac version. so i think the problem is specific to Linux.

Here is the full log of the packaging: [Log.txt](https://github.com/ue4plugins/NdiMedia/files/966180/Log.txt)

To reproduce:
- Create c++ project with unreal 4.15.1 build from source with the cross compiling tool
- Clone NdiMedia to the Plugin folder of the project with branch 4.15 (with the fix for the PCHUsage https://github.com/gundz/NdiMedia/commit/03c62a7e8aa52ee0b61d58612e40393b5fb5fbc3 )
- Compile
- Package project for linux

I'm compiling 4.16 preview right now to test if it works with the master branch, I update this post when it's done.

Edit: same issue with 4.16 preview-2

**Comment by GundlackFlorian** [comment]
In the [Ndimedia.Build.cs line 69](https://github.com/ue4plugins/NdiMedia/blob/master/Source/NdiMedia/NdiMedia.Build.cs#L69)
the path to the linux lib links only the folder, so i edited it like this:
``string LibDir = Path.Combine(NdiDir, "lib", "linux", "x86_64-linux-gnu-5.4");``
``string LibPath = Path.Combine(LibDir, "libndi.a");``
but still the same issue

**Comment by gmpreussner** [comment]
Hey, sorry for the delay - I was on travel. Let me take a look...

**Comment by gmpreussner** [comment]
Couldn't compile for a few days, because my Visual Studio was hosed. Anyway, it should be fixed now. The Build.cs was indeed broken. Also, the Newtek SDK is linked against libstdc++, so I had to include that as well. Newtek might link against libc++ in the future, which should be digestible on more Linux distros.

Let me know if this works for you, thanks!

**Comment by GundlackFlorian** [comment]
Hi !

Just tried and the project was perfectly packaged, i didn't tested the build yet but i let you know if there is an issue.

Thanks !
