### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by GundlackFlorian** [ue4plugins/NdiMedia#17]
Hi !

To not create an issue topic for every issue, so if you don't mind i put them here:

I tried today to compile NdiMedia directly from linux (blank project + plugin) and it don't compile here is the log:

```
Performing 2 actions (5 in parallel)
[1/2] Link libUE4Editor-NdiMedia.so
/usr/bin/ld: /home/gundz/Documents/Unreal Projects/MyProject/Plugins/NdiMedia/ThirdParty/lib/linux/x86_64-linux-gnu-5.4/libndi.a(Processing.NDI.Find.o): réadressage de R_X86_64_32 en vertu de « __gxx_personality_v0 » ne peut être utilisé lors de la création d'un objet partagé; recompilez avec -fPIC
/home/gundz/Documents/Unreal Projects/MyProject/Plugins/NdiMedia/ThirdParty/lib/linux/x86_64-linux-gnu-5.4/libndi.a : erreur lors de l'ajout de symboles : Mauvaise valeur
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: UBT ERROR: Failed to produce item: /home/gundz/Documents/Unreal Projects/MyProject/Plugins/NdiMedia/Binaries/Linux/libUE4Editor-NdiMedia.so
Total build time: 34,06 seconds (Local executor: 0,00 seconds)
LogInit:Warning: Still incompatible or missing module: libUE4Editor-NdiMedia.so
LogInit:Warning: Still incompatible or missing module: libUE4Editor-NdiMediaEditor.so

```

**Comment by gmpreussner** [comment]
I remember seeing this before. I have just received a dynamic DLL version from Newtek, and I'm going to push another change that will replace the static libraries. That should fix the linking related issues on Linux once and for all.

**Comment by GundlackFlorian** [comment]
Okay !

About the crash issue, to be sure it not comes from my code i made a project with a simple blueprint script (level blueprint) that basicaly:
- Ititialize NDIFinder and wait 3 seconds (to be sure to find the sources)
- calls NDIFinder->GetSources, asign the endpoint from the first found source to the NDIMediaSource
- And finaly Open it in the media player and play it (and shows it on the cube)
It work fine without any problem on windows, but crashes always on linux in UNdiMediaFinder::GetSources function

Here is the log
[Log.txt](https://github.com/ue4plugins/NdiMedia/files/1039178/Log.txt)

And if you want, the test project:
https://github.com/gundz/NDILinuxCrash/

**Comment by GundlackFlorian** [comment]
Hi !
Any news about the linux library linking issue ?

**Comment by GundlackFlorian** [comment]
I contacted Newtek, they send me the linux librairies !
