### ISSUE TITLE
No video/audio from NDI Media Source in 4.18 preview 1

### ISSUE THREAD

**Issue by Jonny-Cache** [ue4plugins/NdiMedia#19]
Hey! Great plug-in, I really appreciate all the great support for the Media Framework. However, with the latest code and the first 4.18 preview I'm getting no video while connected to my NDI stream. Actually I seem to be getting a tiny white square that get's blown up when I set the scale to "fit". 

I'm able to see the feed just fine in the NDI Video Monitor, the correct resolution is being detected and changing dynamically in UEditor, and this was working consistently in 4.17.1 release.

Thanks again!

<img width="1420" alt="ndioutput" src="https://user-images.githubusercontent.com/7664715/30792417-63987974-a177-11e7-85fe-b164fd3c1526.png">

PS Connecting to an NDI stream via the "Source Name" doesn't seem to work (either now or before the update). Probably not related to the above issue, but I figured I'd mention it.

<img width="501" alt="ndistream" src="https://user-images.githubusercontent.com/7664715/30792570-87802c00-a178-11e7-9456-012775fef790.png">

**Comment by gmpreussner** [comment]
Should be fixed now, thanks!

**Comment by Jonny-Cache** [comment]
Verified Fixed! 
Thank you kindly! :)
