### ISSUE TITLE
Support for NDI source name?

### ISSUE THREAD

**Issue by num3ric** [ue4plugins/NdiMedia#2]
Hi @gmpreussner,

Will the NDI media source have support for source names, and not IP addresses? I suspect I may be looking at a newer version of the NDI SDK, because NDI sources are identified with strings?

Just starting to dive into this today!

**Comment by num3ric** [comment]
Great, I got the NdiMediaSource to work by reading the sender ip:port off another sample receiver. Sorry for the noise in here.

**Comment by gmpreussner** [comment]
The next version will have a drop-down menu for the source endpoint address that will contain the list of discovered NDI sources. There will also be a new asset type called UNdiMediaFinder that will allow for searching NDI sources from Blueprint.
