### ISSUE TITLE
Plugin 'NdiMedia' failed to load because module 'NdiMedia' could not be found

### ISSUE THREAD

**Issue by JuriaanGregor** [ue4plugins/NdiMedia#21]
Hi there,

I'm currently running Unreal Engine 4.18.3 and I tried to install the plugin as a Engine plugin and as a Project Plugin but both seem to give the issue 'Module can not be found'

OS : Windows 10 x64
UE version : 4.18.3

Thanks !

**Comment by gmpreussner** [comment]
Where did you see this error? Did you actually compile the Engine and/or your project before using the plug-in? Note that code plug-ins currently require a code project in order to work; they do not work with BP-only projects (yet).

**Comment by JuriaanGregor** [comment]
Hi there,

I'm aware that I need to use a Code project. Will take a picture when I'm at work tomorrow of the exact error message.

**Comment by gmpreussner** [comment]
Hi @JuriaanGregor, were you able to resolve this problem?

**Comment by JuriaanGregor** [comment]
Yes the problem has been fixed.
