### ISSUE TITLE
In ue4 media player black screen

### ISSUE THREAD

**Issue by 11storiesup** [ue4plugins/NdiMedia#23]
When selecting source i see the url i want but its stuck black saying preparing

![problem](https://user-images.githubusercontent.com/12405984/36955518-d13301a8-208d-11e8-8451-803c9ca710b6.jpg)

**Comment by Twentystudios** [comment]
I’m getting the same thing here. I’m also using the NDi Test Pattern as source. This is with 4.19, so maybe it isn’t expected to work until a 4.19 version of the plug-in is released?

**Comment by gmpreussner** [comment]
I think this was an incompatibility between NDI 3.0 and NDI 3.5 Preview. I removed the SDK files from this plug-in. They are now required to be installed manually with the official NDI SDK installer. Check the README for details.
