### ISSUE TITLE
Garbled audio 4.18.3

### ISSUE THREAD

**Issue by Jonny-Cache** [ue4plugins/NdiMedia#24]
When streaming to UE4 from OBS using the NDI plugin (localhost), the video is extremely hitch-y and the audio is completely garbled. Testing the same stream with another OBS instance or the "NDI Video Monitor" (shipped with the NDI binaries) shows that the stream is fine and audio is perfect. 

The only place I can reproduce the issue is in the UE4 editor while attempting to monitor the stream in the "Media Player" UI. 

Changing the Bandwidth or Source Name/Endpoint in the NDIMediaSource asset in UEd doesn't seem to have any affect.

Repro:
- Install the OBS and the NDI Plugin
- Start a stream via Settings > NDI(tm) Plugin
- Open UE4 Editor and create an "NDIMediaSource" and a "Media Player" asset
- Configure the NDI Media Source to connect to the stream
- Check the stream in the Media Player asset

Observed:
- Audio in UE4 Editor from the stream is garbled and segmented
- Video hitches, updating every .3 seconds or so

Note:
- Big fan, love the plugin, trying to get the most out of it :D
- Looking forward to 4.19 support.

**Comment by gmpreussner** [comment]
I was able to reproduce the problem in UE4. Video is fine, but audio is garbled. Interestingly, I also reproduced it in NDI Studio Monitor. However, I already have a newer version installed that is not yet released to the public. As the NdiMedia plug-in is also using pre-release SDK libraries, I believe that this might be an incompatibility between NDI 3.0 and 3.5.

I am still working on the 4.19 release. I am planning to remove the bundled binaries and require the installation of the NDI Redistributable instead. This might resolve the current issues. I will update this thread when I have more details.

**Comment by gmpreussner** [comment]
The 4.19 release is now out. I removed the SDK 3.5 files from the plug-in. They are now required to be installed manually via the official NDI SDK installer (current version is 3.0, but 3.5 Final should be out in a few days). Please see the updated README for details, thanks!
