### ISSUE TITLE
Multiple Outputs Simultaneous

### ISSUE THREAD

**Issue by martinussuijkerbuijk** [ue4plugins/NdiMedia#34]
Since every Broadcast actor is associated with a Player Controller, I cannot send multiple views simultaneously. Instead you can only iterate over the same NDI source on the receiver side. Is there a way e to broadcast multiple camera views as separate NDI sources?

**Comment by tsky1971** [comment]
Hi,
try the NDI SDK Sample for Unreal Engine. You can define multiple Cameras/Sources in the scene. It seems not possible to create at runtime Camera/Sources.
It is possible to control the cameras as PTZ-Cameras with the Studio-Monitor WebInterface, if you implement the missing function in the sources.

T.

**Comment by martinussuijkerbuijk** [comment]
Thank you for your prompt response. There's no issue creating multiple camera sources the only thing is that at runtime only one stream (NDI Actor View point) is generated and available as NDI source. Only one NDI camera component can be instantiated when the player controller is loaded at runtime. Have you managed to pull it off? It should be possible I guess.

**Comment by martinussuijkerbuijk** [comment]
Well this is embarrassing, I forgot to apply the broadcast source to the broadcast component. It works perfectly.
