### ISSUE TITLE
Audio seems to lose sync

### ISSUE THREAD

**Issue by coreyx** [ue4plugins/NdiMedia#5]
I have not been able to reproduce this issue since it first happened, but at least once I heard the audio desync from the video by a few seconds or so. I'll keep trying to reproduce or identify what caused this failure.

Using the latest commit [693233d](https://github.com/ue4plugins/NdiMedia/tree/693233dd55291a596377500a4f7608dafd6e35e0) and UE 4.14 Preview 2

**Comment by gmpreussner** [comment]
I don't have a good way to test this right now, but I think it should be fixed.

**Comment by coreyx** [comment]
I still haven't seen this issue more than once. I am not sure what caused it. I think we can close this one for now and reopen if the issue comes up again.

**Comment by gmpreussner** [comment]
I think the main issue was that the audio buffers didn't get flushed on pause/resume. There also wasn't proper suspending of the audio thread while media is paused or while there was no audio sink assigned.
