### ISSUE TITLE
Intermittent crashing

### ISSUE THREAD

**Issue by coreyx** [ue4plugins/NdiMedia#6]
Every once and a while, the UE4 editor crashes when I stop from playing in PIE mode, using Unreal 4.14 Preview 2 and commit [693233d](https://github.com/ue4plugins/NdiMedia/tree/693233dd55291a596377500a4f7608dafd6e35e0).

This is somewhat rare, but it has happened a few times now.

I suspect the issue is in the audio portion of the plugin as I never encountered these issues before it was added, and the other open issues (issue #3, #4, #5) having to due with the audio functionality may also be related.

For some reason, even though I have debug symbols for both engine and the plugin, there is no stack trace in the UE4 Crash Reporter window.

I guess I'll have to run in the debugger and see if I can catch the crash.

**Comment by gmpreussner** [comment]
I found and fixed the obvious offender. See if you're still getting any crashes.

**Comment by gmpreussner** [comment]
I'm going to close this one out, too. If you find any other issues, please let me know. Otherwise I'll post a 4.14 release for NdiMedia - probably end of day tomorrow. Thanks a lot for your help!
