### ISSUE TITLE
Audio volume seems to be low

### ISSUE THREAD

**Issue by coreyx** [ue4plugins/NdiMedia#8]
When playing an NDI video+audio source through this plugin, it is much lower volume than other playback systems, and even a local file played back in UE4.

For reference, I get equal volume from playing the same stream in any other NDI receiver application vs. playing the exact same source video file in VLC with 100% volume.

All of these are playing through the same audio output device on my system when I perform the tests.

In UE4, I'm playing the sound unaltered through an audio component with Volume Multiplier: 1.0. No attenuation is being applied and there are no effects like reverb.

It also makes no difference if I assign a sound class or not (with volume also at 1.0, of course). The volume is the same. However, I know the sound class is working, as if I set volume to 0.1, it is attenuated as expected.

I've also tried playing around with audio-related world settings, project settings, editor settings, etc. to no avail. I am not getting my expected result of playing back the NDI stream at 1.0 volume having an equal volume to these other playback systems. Sound volume is always very low. By the way, UE4's audio settings are very spread out which makes everything really confusing and inconvenient to work with.

I even tried adjusting the editor's "Real Time Audio" setting (in the dropdown menu of the Settings button in the editor) and that didn't seem to affect anything at all.

Edit: I did some additional testing. I created a media player for both NDI sources and one for local file sources in UE4. I then played the same exact file over NDI and over the local file source. The NDI source, when played back in UE4, is lower volume than the local file source--not what I would expect. However, if I play the same NDI stream in a different player (not UE4), the volume is the same as the original file, as I would expect, so I know the source NDI stream is not to blame.

Local file playback via UE4's Media Framework also seems to have a problem with lower than usual volumes. If I play the same movie on the system locally with unity gain in a player like VLC, or any other player at 100%, the effective volume is MUCH higher than in UE4.

But the NDI playback in UE4 is even lower volume yet than the local file playback. So I think there is a problem in both UE4's Media Framework and in the NDI plugin itself. In other words, it seems UE4 plays back media at low volumes even when using a local file, but the NDI plugin plays back at even lower volumes yet.

Using UE4 4.14 Preview 3 and commit [86350e1](https://github.com/ue4plugins/NdiMedia/commit/86350e1115393f8d3c66f9ce2365be796c509a7d).

**Comment by gmpreussner** [comment]
How many audio channels are in your NDI stream?

**Comment by coreyx** [comment]
I'm just playing 720p mp4 video with a 125Kbps, 44Khz stereo audio track. I'm not sure what NDI does with it when streaming, but I assume it's all stereo from there.

**Comment by gmpreussner** [comment]
Can you try playing with [this value](https://github.com/ue4plugins/NdiMedia/blob/master/Source/NdiMedia/Private/Player/NdiMediaPlayer.cpp#L793)? I'm using the recommended value of 20 db there, but maybe that's not correct.

**Comment by coreyx** [comment]
Hey there, I won't have a chance to do that for at least another week as I'm currently hammered with a tight deadline. But I am looking forward to get back to the project I was using this for and I'll get back to you on this if you still need help.

**Comment by gmpreussner** [comment]
I added a per-NdiMediaSource setting for configuring the input audio reference level. The default for value for this is 5 dB, and the resulting output volume is pretty close to what the Newtek Studio Monitor produces. Note that the new Audio Mixer in UE4 adds its own headroom to audio samples, so the 20 dB recommended for audio input by Newtek is too much. I think that 4.5 dB would be an even better match, but the NDI SDK API only accepts integer values at this time, so 5 dB is as good as it gets.
