### ISSUE TITLE
Mixing NDI Media Source with File Media Source in playlist results in crash when switching sources

### ISSUE THREAD

**Issue by coreyx** [ue4plugins/NdiMedia#9]
Steps to reproduce:

1. Create a Media Playlist.
2. Add a File Media Source to the playlist.
3. Add an NDI Media Source to the playlist.
4. Use a Media Player to open the playlist (from Blueprint).

When the File Media Source finishes playing, the Media Player switches to the NDI Media Source and I believe tries to play it with the same player it was using for the File Media Source (WmfMediaPlayer), which causes the editor to crash.

Environment: Windows, 
Unreal Engine version: 4.14
NdiMedia plugin (commit 43f2f19).

**Comment by coreyx** [comment]
Here is the stack trace:
Access violation - code c0000005 (first/second chance not available)

UE4Editor_WmfMedia!TQueue<TFunction<void __cdecl(void)>,1>::Dequeue() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\core\public\containers\queue.h:68]
UE4Editor_WmfMedia!FWmfMediaPlayer::Tick() [d:\build\++ue4+release-4.14+compile\sync\engine\plugins\media\wmfmedia\source\wmfmedia\private\player\wmfmediaplayer.cpp:46]
UE4Editor_Core!FTicker::Tick() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\core\private\containers\ticker.cpp:81]
UE4Editor!FEngineLoop::Tick() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\launch\private\launchengineloop.cpp:2963]
UE4Editor!GuardedMain() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\launch\private\launch.cpp:152]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:126]
UE4Editor!WinMain() [d:\build\++ue4+release-4.14+compile\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:202]
UE4Editor!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:264]
kernel32
ntdll

**Comment by coreyx** [comment]
The same issue happens when I open/play a File Media Source followed by an NDI Media Source on the same Media Player without the use of the playlist.

However, the reverse order (playing an NDI Media Source, followed by switching to a File Media Source) does not trigger a crash.

**Comment by gmpreussner** [comment]
This used to be a bug in WmfMedia. Fixed in 4.15.
